# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Exercises with no solutions
no_solution:
  - "https://dcsem-solutions.weecology.org/solutions/Tidy-data-improving-messy-data-SQL"
  - "https://dcsem-solutions.weecology.org/solutions/Qaqc-data-entry-validation-in-excel-SQL"
  - "https://dcsem-solutions.weecology.org/solutions/Tidy-data-clean-up-SQL"

# Setup
title:            Coding for Applied Economists
description:      'Making applied economics less dismal'
url:              https://github.com/jdavidm/learn-stata
baseurl:          /learn-stata
email:            jdmichler@arizona.edu
feedbackurl:      https://docs.google.com/forms/d/1hST-wT3WkGsp0XY0gyRUEREEE4MxsenmKjn10IgjSPU/
author:
  name:           'Jeffrey D. Michler'
  url:            https://twitter.com/jdmichler

github:
  repo:           https://github.com/jdavidm/learn-stata
  #               Be sure the 'Issues' feature is activated in 'Settings'

